AllCops:
  Exclude:
  - 'db/**/*'
  - 'Gemfile'
  - 'vendor/**/*'
  - 'lib/tasks/ok.rake'

Metrics/LineLength:
  Max: 150

Style/Documentation:
 Enabled: false

Style/PredicateName:
  NamePrefixBlacklist:
  - get_
  - set_
